# Xem nhanh dữ liệu trong Postgres — table browser

Notebook này **chỉ đọc** (không ghi/sửa gì) — mục đích duy nhất là cho bạn xem nhanh nội
dung thật của từng bảng trong Postgres, sau đợt sửa lỗi migration `pdf_document_id`
(2026-07-30/31, xem `docs/PROGRESS.md` phần cuối để biết bối cảnh đầy đủ: 6 lỗi thật đã
sửa, kết thúc bằng `overall ok=True` trong `data_quality_report.py`).

Khác với `notebooks/01_data_inventory_eda.ipynb` (phân tích/EDA sâu, mục đích quyết định
kiến trúc ML) — notebook này đơn giản hơn nhiều: liệt kê bảng, đếm dòng, xem mẫu dữ liệu.
Không vẽ biểu đồ, không phân tích thống kê.

Chạy trực tiếp trên máy đã có:
- Docker Postgres đang chạy (`docker compose up -d`)
- `.venv` của project đã cài đủ dependency
- Kernel Jupyter trỏ vào `.venv/bin/python` của project

Mỗi cell được bọc `try/except` — một bảng lỗi/rỗng không làm vỡ cả notebook.

In [1]:
import sys
import traceback
from pathlib import Path

PROJECT_ROOT = Path.cwd()
if not (PROJECT_ROOT / "src").exists():
    PROJECT_ROOT = PROJECT_ROOT.parent
assert (PROJECT_ROOT / "src").exists(), "Chay notebook nay tu thu muc goc project (co folder src/)"
sys.path.insert(0, str(PROJECT_ROOT))

import pandas as pd

pd.set_option("display.max_columns", 60)
pd.set_option("display.width", 160)
pd.set_option("display.max_colwidth", 80)

from src.core.db import engine, check_connection

check_connection()

OK - connected to localhost:5432/financial_db

True

## 1. Danh sách toàn bộ bảng + số dòng

Lấy động từ `information_schema` - tự cập nhật khi có bảng mới, không cần sửa tay notebook
này mỗi khi schema đổi.

In [2]:
try:
    table_names = pd.read_sql(
        """SELECT table_name FROM information_schema.tables
           WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
           ORDER BY table_name""", engine
    )["table_name"].tolist()

    counts = []
    for t in table_names:
        try:
            n = pd.read_sql(f"SELECT count(*) AS n FROM {t}", engine)["n"].iloc[0]
        except Exception as e:
            n = f"loi: {type(e).__name__}"
        counts.append({"table": t, "n_rows": n})

    overview = pd.DataFrame(counts)
    display(overview)
except Exception as e:
    print(f"[canh bao] khong liet ke duoc bang: {type(e).__name__}: {e}")
    traceback.print_exc()
    table_names = []

                        table  n_rows
0      causal_experiment_runs       0
1       causal_panel_snapshot       0
2                   companies     222
3      company_price_snapshot   39575
4           disclosure_chunks  661657
5                 disclosures    3155
6        financial_line_items  283732
7            financial_ratios  136369
8               ingestion_log     432
9            macro_indicators     264
10              pdf_documents    3572
11        predictive_features       0
12  predictive_split_manifest       0

## 2. `pdf_documents` — bảng vừa sửa xong đợt migration này

Chú ý đặc biệt: cột `pdf_hash` — dòng nào bằng `MISSING_SOURCE_PDF_HASH_SENTINEL`
(64 số 0) nghĩa là file PDF gốc đã xác nhận không còn, đăng ký qua
`--allow-missing-pdf-placeholder` (xem `scripts/register_pdf_documents.py`).

In [3]:
try:
    from scripts.register_pdf_documents import MISSING_SOURCE_PDF_HASH_SENTINEL

    pdf_docs = pd.read_sql("SELECT * FROM pdf_documents ORDER BY id", engine)
    print(f"pdf_documents: {len(pdf_docs):,} dong")

    n_placeholder = (pdf_docs["pdf_hash"] == MISSING_SOURCE_PDF_HASH_SENTINEL).sum()
    print(f"  - {n_placeholder:,} dong dung placeholder hash (PDF goc da mat, xem cot pdf_hash)")
    print(f"  - {(~pdf_docs['is_active']).sum():,} dong is_active=FALSE (PDF da bi xoa khoi --input)")

    print("\nMau 20 dong dau:")
    display(pdf_docs.head(20))

    print("\n20 dong dung placeholder hash (neu co) - nhung file KHONG con PDF goc:")
    display(pdf_docs[pdf_docs["pdf_hash"] == MISSING_SOURCE_PDF_HASH_SENTINEL].head(20))
except Exception as e:
    print(f"[canh bao] khong doc duoc pdf_documents: {type(e).__name__}: {e}")
    traceback.print_exc()
    pdf_docs = pd.DataFrame()

pdf_documents: 3,572 dong
  - 2,890 dong dung placeholder hash (PDF goc da mat, xem cot pdf_hash)
  - 0 dong is_active=FALSE (PDF da bi xoa khoi --input)

Mau 20 dong dau:

,id,source_file,pdf_hash,ticker,doctype,fiscal_year,n_pages_total,extraction_version,extracted_at,document_version,is_active,linked_disclosure_id,updated_at
0,2,01.-Thong-bao-moi-hop-DHDCD-2023_VN-Final.pdf,7243c1bdf983c43976d2915b76b835d2b902af79d475e07accfa6ff12af79922,UNKNOWN,other,2023.0,1,,2026-07-30 07:36:06.838922+00:00,1,True,NaN,2026-07-30 07:36:06.838922+00:00
1,3,01.-Thong-bao-moi-hop-DHDCD-2024_VN-Final.pdf,d6736c805129c97eec9921c8587313c5effc5cf032c7abe68669d1fa175377a8,UNKNOWN,other,2024.0,1,,2026-07-30 07:36:06.838922+00:00,1,True,NaN,2026-07-30 07:36:06.838922+00:00
2,4,04.-HDSD-Bvote-cho-CD-VN.pdf,065c8a577a8ff57cf4db37a25e518cf6477893bbbd904c75a21d4b3080766df5,UNKNOWN,other,NaN,6,,2026-07-30 07:36:06.838922+00:00,1,True,NaN,2026-07-30 07:36:06.838922+00:00
3,5,0_Ban_CBTT_Tai_lieu_AGM_2026_f295e68b32.pdf,63fa42bdbe4a098eddf6eccfe025b8747ca303da8b39a6f78ab43b1f06188177,UNKNOWN,other,2026.0,1,,2026-07-30 07:36:06.838922+00:00,1,True,NaN,2026-07-30 07:36:06.838922+00:00
4,6,10_AGM_2026_Quy_che_to_chuc_dai_hoi_5765b92317.pdf,b20fb9a9051e3179c29c439ad71a224409aae56d1e28ca6149d452a445e92349,UNKNOWN,other,2026.0,17,,2026-07-30 07:36:06.838922+00:00,1,True,NaN,2026-07-30 07:36:06.838922+00:00
5,7,10_aah_2024_5_4_bbab271_12__to_trinh_kqsxkd_signed.pdf,3fd829beeaaaab9f508c9e21d28ef1146b55664083db5b646f9b187b673d654b,AAH,other,2024.0,1,,2026-07-30 07:36:06.838922+00:00,1,True,38.0,2026-07-30 07:36:06.838922+00:00
6,8,11_AGM_2026_Notice_of_candidate_nomination_59bf87a429.pdf,1b81a86045b84d4f7e0b2ab4e2d6aa562bfcf994bda8c7ee894465029e0d96d1,UNKNOWN,other,2026.0,1,,2026-07-30 07:36:06.838922+00:00,1,True,NaN,2026-07-30 07:36:06.838922+00:00
7,9,11_AGM_2026_Thong_bao_de_cu_ung_cu_HDQT_VN_f5763c4c27.pdf,667a6c9d407dac2945f1bbdc6e58eae855dbfa01564edc239c3b3f8700973860,UNKNOWN,other,2026.0,1,,2026-07-30 07:36:06.838922+00:00,1,True,NaN,2026-07-30 07:36:06.838922+00:00
8,10,11_aah_2024_5_4_c3757c1_08__bc_ban_tgd_signed.pdf,3ffa767987072af0fd8297c3e2ea36931fd05a3ca387519a077676d7d82f1749,AAH,other,2024.0,4,,2026-07-30 07:36:06.838922+00:00,1,True,38.0,2026-07-30 07:36:06.838922+00:00
9,11,12_VNM_AGM_2026_Mau_1_A_Thu_de_cu_cua_co_dong_VN_Co_dong_don_le_10b9d06fd2.pdf,e8def24080e3e56c136d6d0e7bd607bb7a2baa6a156a9f55b5eaf6913d70ab1c,VNM,other,2026.0,1,,2026-07-30 07:36:06.838922+00:00,1,True,NaN,2026-07-30 07:36:06.838922+00:00
10,12,13_VNM_AGM_2026_Mau_1_B_Thu_de_cu_cua_co_dong_VN_Co_dong_nhom_0c507f3faa.pdf,b9209e00e7bae2b0eb96f1170c45308ed25aca4f48c5ce8220ffb51bf32bd8ff,VNM,other,2026.0,1,,2026-07-30 07:36:06.838922+00:00,1,True,NaN,2026-07-30 07:36:06.838922+00:00
11,13,13_aah_2024_5_4_f5db49e_02__bbh_dhdcd_signed.pdf,d53ba2bf683f12dd0dd35be1cbe392e5488cc60146f95ff77e0033852385b051,AAH,other,2024.0,8,,2026-07-30 07:36:06.838922+00:00,1,True,38.0,2026-07-30 07:36:06.838922+00:00
12,14,14_VNM_AGM_2026_Form_2_Candidate_Profile_da5c06e639.pdf,55ddd526f6cd86437ff6e21d3d286527bc56f2552acb9f5fc24e549218942355,VNM,other,2026.0,2,,2026-07-30 07:36:06.838922+00:00,1,True,NaN,2026-07-30 07:36:06.838922+00:00
13,15,14_VNM_AGM_2026_Mau_02_So_yeu_ly_lich_VN_777a33a885.pdf,604d053930859f38637b02dbfd6feb734ddd6fb15685cdbb6b99c90038f04e04,VNM,other,2026.0,2,,2026-07-30 07:36:06.838922+00:00,1,True,NaN,2026-07-30 07:36:06.838922+00:00
14,16,15_VNM_AGM_2026_Mau_03_Ke_khai_thong_tin_ung_vien_VN_a1a8c0b743.pdf,33288cc338fb99851edc72334753bff12a54702760c90c88f5b5433432fa3b39,VNM,other,2026.0,3,,2026-07-30 07:36:06.838922+00:00,1,True,NaN,2026-07-30 07:36:06.838922+00:00
15,17,1604_ENG_VCB_Annual-Report-2025_v2.pdf,63988b347b3743391dfec3647fdcdd1f2b06af09ead9a9f52c8bf8fd86352a27,UNKNOWN,other,2025.0,112,,2026-07-30 07:36:06.838922+00:00,1,True,NaN,2026-07-30 07:36:06.838922+00:00
16,18,1_VNM_AGM_2026_AGM_Invitation_Letter_2adb448d1c.pdf,38ee680bdc7c6cebf49ddbf5ac8f4df19f430a86bc59c678a778e00268f1e0c0,VNM,other,2026.0,1,,2026-07-30 07:36:06.838922+00:00,1,True,NaN,2026-07-30 07:36:06.838922+00:00
17,19,1_VNM_AGM_2026_Thu_moi_hop_DHDCD_VN_bdeabe34dd.pdf,88346c79946a83fa14014638267e37d6778fbbcea156c2616ce1b651bec9b640,VNM,other,2026.0,1,,2026-07-30 07:36:06.838922+00:00,1,True,NaN,2026-07-30 07:36:06.838922+00:00
18,20,1_aah_2024_7_22_24641ac_cbtt_0805da_ky.pdf,1807525f6d1c36cac8aeeac61cf4335b64f0bf915738a44e9b4d683522b90701,AAH,other,2024.0,5,,2026-07-30 07:36:06.838922+00:00,1,True,38.0,2026-07-30 07:36:06.838922+00:00
19,21,1_aah_2024_8_19_33a98dd_giai_trinh_chenh_lech_ln_va_ln_tu_lo_sang_lai_cung_k...,09964ea2b0baa3caeeda3670f2cd03fb60ebfb951cb45ccdadce1effff23a1b0,AAH,kqkd_explanation,2024.0,2,,2026-07-30 07:36:06.838922+00:00,1,True,38.0,2026-07-30 07:36:06.838922+00:00

20 dong dung placeholder hash (neu co) - nhung file KHONG con PDF goc:

,id,source_file,pdf_hash,ticker,doctype,fiscal_year,n_pages_total,extraction_version,extracted_at,document_version,is_active,linked_disclosure_id,updated_at
682,1707,1_aas_2022_3_31_503a68a_bctlattc_2021__cks,0000000000000000000000000000000000000000000000000000000000000000,AAS,other,2021.0,28,,2026-07-30 09:39:33.456660+00:00,1,True,NaN,2026-07-30 09:39:33.456660+00:00
683,1708,1_aav_2025_3_31_1029b13_en_consolidatedauditedfinancialstatements_2024,0000000000000000000000000000000000000000000000000000000000000000,AAV,other,2024.0,44,,2026-07-30 09:39:33.456660+00:00,1,True,95.0,2026-07-30 09:39:33.456660+00:00
684,1709,1_aav_2025_3_31_958df1a_en_separateauditedfinancialstatements_2024,0000000000000000000000000000000000000000000000000000000000000000,AAV,other,2024.0,41,,2026-07-30 09:39:33.456660+00:00,1,True,95.0,2026-07-30 09:39:33.456660+00:00
685,1710,1_abc_2025_3_31_4be07a6_financial__statement_2024_audited,0000000000000000000000000000000000000000000000000000000000000000,ABC,other,2024.0,45,,2026-07-30 09:39:33.456660+00:00,1,True,397.0,2026-07-30 09:39:33.456660+00:00
686,1711,1_abc_2026_3_26_28649d6_vi_baocaotaichinhkiemtoan2025,0000000000000000000000000000000000000000000000000000000000000000,ABC,financial_statement,2025.0,46,,2026-07-30 09:39:33.456660+00:00,1,True,404.0,2026-07-30 09:39:33.456660+00:00
687,1712,1_acg_2022_3_28_2703ca7_acg_bctc_hop_nhat_2021_signed,0000000000000000000000000000000000000000000000000000000000000000,ACG,other,2021.0,47,,2026-07-30 09:39:33.456660+00:00,1,True,NaN,2026-07-30 09:39:33.456660+00:00
688,1713,1.ACV_2020.4.14_b666973_BCTC_hop_nhat_2019da_nen,0000000000000000000000000000000000000000000000000000000000000000,ACV,other,2019.0,64,,2026-07-30 09:39:33.456660+00:00,1,True,NaN,2026-07-30 09:39:33.456660+00:00
689,1714,1.ACV_2021.4.12_1f69703_ACVBCTC_Hop_nhat_nam_2020_da_duoc_kiem_toancompressed,0000000000000000000000000000000000000000000000000000000000000000,ACV,other,2020.0,62,,2026-07-30 09:39:33.456660+00:00,1,True,NaN,2026-07-30 09:39:33.456660+00:00
690,1715,1_acv_2022_4_5_5f2b45d_acv__bao_cao_tai_chinh_hop_nhat,0000000000000000000000000000000000000000000000000000000000000000,ACV,financial_statement,2022.0,62,,2026-07-30 09:39:33.456660+00:00,1,True,NaN,2026-07-30 09:39:33.456660+00:00
691,1716,1_acv_2023_3_31_0884ea6_acv__bao_cao_tai_chinh_hop_nhat_2022,0000000000000000000000000000000000000000000000000000000000000000,ACV,financial_statement,2022.0,65,,2026-07-30 09:39:33.456660+00:00,1,True,NaN,2026-07-30 09:39:33.456660+00:00
692,1717,1_acv_2025_4_3_0363334_vi_baocaotaichinhcongtyme_kiemtoan_2024,0000000000000000000000000000000000000000000000000000000000000000,ACV,financial_statement,2024.0,55,,2026-07-30 09:39:33.456660+00:00,1,True,549.0,2026-07-30 09:39:33.456660+00:00
693,1718,1_acv_2025_4_3_60af8b9_vi_baocaotaichinhhopnhat_kiemtoan_2024,0000000000000000000000000000000000000000000000000000000000000000,ACV,financial_statement,2024.0,57,,2026-07-30 09:39:33.456660+00:00,1,True,549.0,2026-07-30 09:39:33.456660+00:00
694,1719,1_adc_2025_3_28_21e16b3_vi_baocaotaichinh_kiemtoan_2024,0000000000000000000000000000000000000000000000000000000000000000,ADC,financial_statement,2024.0,32,,2026-07-30 09:39:33.456660+00:00,1,True,564.0,2026-07-30 09:39:33.456660+00:00
695,1720,1_afx_2024_3_30_6493dca_bctc_da_duoc_kiem_toan_ngay_31122023,0000000000000000000000000000000000000000000000000000000000000000,AFX,other,2024.0,41,,2026-07-30 09:39:33.456660+00:00,1,True,624.0,2026-07-30 09:39:33.456660+00:00
696,1721,1_afx_2025_3_28_4f93f82_vi_bctc_da_duoc_kiem_toan_31122024_signed,0000000000000000000000000000000000000000000000000000000000000000,AFX,other,2025.0,45,,2026-07-30 09:39:33.456660+00:00,1,True,631.0,2026-07-30 09:39:33.456660+00:00
697,1722,1_agf_2022_3_31_1f9a47a_bctc_ky_ke_toan_01_01_2021__31_12_2021__kiem_toansign,0000000000000000000000000000000000000000000000000000000000000000,AGF,other,2021.0,40,,2026-07-30 09:39:33.456660+00:00,1,True,NaN,2026-07-30 09:39:33.456660+00:00
698,1723,1_agf_2023_3_27_8cb5288_bctc_ky_ke_toan_01_01_2022__31_12_2022__kiem_toan__sign,0000000000000000000000000000000000000000000000000000000000000000,AGF,other,2022.0,42,,2026-07-30 09:39:33.456660+00:00,1,True,NaN,2026-07-30 09:39:33.456660+00:00
699,1724,1_agf_2024_3_29_4129fa5_bctc_nam_2023_da_kiem_toansign,0000000000000000000000000000000000000000000000000000000000000000,AGF,other,2023.0,43,,2026-07-30 09:39:33.456660+00:00,1,True,NaN,2026-07-30 09:39:33.456660+00:00
700,1725,1_agf_2025_4_2_83bfd05_vi_baocaotaichinh_kiemtoan_2024sign,0000000000000000000000000000000000000000000000000000000000000000,AGF,financial_statement,2024.0,43,,2026-07-30 09:39:33.456660+00:00,1,True,639.0,2026-07-30 09:39:33.456660+00:00
701,1726,1_agm_2026_3_13_3dfe135_bctc_rieng__kiem_toan_2025_tv_sign,0000000000000000000000000000000000000000000000000000000000000000,AGM,other,2025.0,55,,2026-07-30 09:39:33.456660+00:00,1,True,676.0,2026-07-30 09:39:33.456660+00:00

## 3. `disclosure_chunks` — corpus RAG (mẫu, KHÔNG load hết 661k+ dòng vào RAM)

Bảng này rất lớn — luôn dùng `LIMIT` hoặc lọc theo `ticker` khi xem, đừng `SELECT *` không
giới hạn.

In [4]:
try:
    chunks_sample = pd.read_sql(
        """SELECT id, ticker, doctype, source_file, page, chunk_index, char_count,
                  pdf_document_id, (embedding IS NOT NULL) AS has_embedding,
                  (chunk_hash IS NOT NULL) AS has_chunk_hash
           FROM disclosure_chunks ORDER BY id LIMIT 20""", engine
    )
    print("Mau 20 dong dau (khong lay chunk_text/embedding day du - qua nang):")
    display(chunks_sample)

    total_chunks = pd.read_sql("SELECT count(*) AS n FROM disclosure_chunks", engine)["n"].iloc[0]
    print(f"\nTong so chunk: {total_chunks:,}")
except Exception as e:
    print(f"[canh bao] khong doc duoc disclosure_chunks: {type(e).__name__}: {e}")
    traceback.print_exc()

Mau 20 dong dau (khong lay chunk_text/embedding day du - qua nang):

    id ticker              doctype                       source_file  page  chunk_index  char_count  pdf_document_id  has_embedding  has_chunk_hash
0    1    A32  financial_statement  A32_Baocaotaichinh_2017_Kiemtoan     1            0         273             2371           True            True
1    2    A32  financial_statement  A32_Baocaotaichinh_2017_Kiemtoan    10            0         750             2371           True            True
2    3    A32  financial_statement  A32_Baocaotaichinh_2017_Kiemtoan    10            1         782             2371           True            True
3    4    A32  financial_statement  A32_Baocaotaichinh_2017_Kiemtoan    10            2         796             2371           True            True
4    5    A32  financial_statement  A32_Baocaotaichinh_2017_Kiemtoan    10            3         791             2371           True            True
5    6    A32  financial_statement  A32_Baocaotaichinh_2017_Kiemtoan    11            0         721             2371           True            True
6    7    A32  financial_statement  A32_Baocaotaichinh_2017_Kiemtoan    11            1         718             2371           True            True
7    8    A32  financial_statement  A32_Baocaotaichinh_2017_Kiemtoan    11            2         345             2371           True            True
8    9    A32  financial_statement  A32_Baocaotaichinh_2017_Kiemtoan    11            3         120             2371           True            True
9   10    A32  financial_statement  A32_Baocaotaichinh_2017_Kiemtoan    11            4         119             2371           True            True
10  11    A32  financial_statement  A32_Baocaotaichinh_2017_Kiemtoan    11            5         118             2371           True            True
11  12    A32  financial_statement  A32_Baocaotaichinh_2017_Kiemtoan    11            6         116             2371           True            True
12  13    A32  financial_statement  A32_Baocaotaichinh_2017_Kiemtoan    11            7         116             2371           True            True
13  14    A32  financial_statement  A32_Baocaotaichinh_2017_Kiemtoan    11            8         115             2371           True            True
14  15    A32  financial_statement  A32_Baocaotaichinh_2017_Kiemtoan    11            9         114             2371           True            True
15  16    A32  financial_statement  A32_Baocaotaichinh_2017_Kiemtoan    11           10         112             2371           True            True
16  17    A32  financial_statement  A32_Baocaotaichinh_2017_Kiemtoan    11           11         112             2371           True            True
17  18    A32  financial_statement  A32_Baocaotaichinh_2017_Kiemtoan    11           12         111             2371           True            True
18  19    A32  financial_statement  A32_Baocaotaichinh_2017_Kiemtoan    11           13         110             2371           True            True
19  20    A32  financial_statement  A32_Baocaotaichinh_2017_Kiemtoan    11           14         109             2371           True            True

Tong so chunk: 661,657

In [5]:
# Xem chunk theo 1 ticker cu the - sua TICKER ben duoi
TICKER = "VNM"

try:
    by_ticker = pd.read_sql(
        """SELECT id, ticker, doctype, source_file, page, chunk_index, char_count
           FROM disclosure_chunks WHERE ticker = %(ticker)s ORDER BY source_file, page, chunk_index LIMIT 50""",
        engine, params={"ticker": TICKER}
    )
    print(f"disclosure_chunks WHERE ticker = '{TICKER}': {len(by_ticker)} dong (hien 50 dau)")
    display(by_ticker)
except Exception as e:
    print(f"[canh bao] khong query duoc theo ticker: {type(e).__name__}: {e}")
    traceback.print_exc()

disclosure_chunks WHERE ticker = 'VNM': 50 dong (hien 50 dau)

         id ticker doctype                    source_file  page  chunk_index  char_count
0   1378234    VNM   other  BCTC HOP NHAT 31.12.2019 - VN     1            0         131
1   1378272    VNM   other  BCTC HOP NHAT 31.12.2019 - VN     2            0         334
2   1378314    VNM   other  BCTC HOP NHAT 31.12.2019 - VN     3            0         798
3   1378315    VNM   other  BCTC HOP NHAT 31.12.2019 - VN     3            1         797
4   1378316    VNM   other  BCTC HOP NHAT 31.12.2019 - VN     3            2         794
5   1378357    VNM   other  BCTC HOP NHAT 31.12.2019 - VN     4            0         796
6   1378358    VNM   other  BCTC HOP NHAT 31.12.2019 - VN     4            1         797
7   1378359    VNM   other  BCTC HOP NHAT 31.12.2019 - VN     4            2         754
8   1378401    VNM   other  BCTC HOP NHAT 31.12.2019 - VN     5            0         797
9   1378402    VNM   other  BCTC HOP NHAT 31.12.2019 - VN     5            1         795
10  1378403    VNM   other  BCTC HOP NHAT 31.12.2019 - VN     5            2         797
11  1378404    VNM   other  BCTC HOP NHAT 31.12.2019 - VN     5            3         799
12  1378405    VNM   other  BCTC HOP NHAT 31.12.2019 - VN     5            4         235
13  1378444    VNM   other  BCTC HOP NHAT 31.12.2019 - VN     6            0         798
14  1378445    VNM   other  BCTC HOP NHAT 31.12.2019 - VN     6            1         164
15  1378462    VNM   other  BCTC HOP NHAT 31.12.2019 - VN     7            0         755
16  1378463    VNM   other  BCTC HOP NHAT 31.12.2019 - VN     7            1         733
17  1378464    VNM   other  BCTC HOP NHAT 31.12.2019 - VN     7            2         784
18  1378465    VNM   other  BCTC HOP NHAT 31.12.2019 - VN     7            3         795
19  1378466    VNM   other  BCTC HOP NHAT 31.12.2019 - VN     7            4         307
20  1378467    VNM   other  BCTC HOP NHAT 31.12.2019 - VN     8            0         733
21  1378468    VNM   other  BCTC HOP NHAT 31.12.2019 - VN     8            1         783
22  1378469    VNM   other  BCTC HOP NHAT 31.12.2019 - VN     8            2         762
23  1378470    VNM   other  BCTC HOP NHAT 31.12.2019 - VN     8            3         735
24  1378471    VNM   other  BCTC HOP NHAT 31.12.2019 - VN     8            4         730
25  1378472    VNM   other  BCTC HOP NHAT 31.12.2019 - VN     8            5         533
26  1378473    VNM   other  BCTC HOP NHAT 31.12.2019 - VN     9            0         747
27  1378474    VNM   other  BCTC HOP NHAT 31.12.2019 - VN     9            1         699
28  1378475    VNM   other  BCTC HOP NHAT 31.12.2019 - VN     9            2         773
29  1378476    VNM   other  BCTC HOP NHAT 31.12.2019 - VN     9            3         753
30  1378477    VNM   other  BCTC HOP NHAT 31.12.2019 - VN     9            4         793
31  1378478    VNM   other  BCTC HOP NHAT 31.12.2019 - VN     9            5         798
32  1378479    VNM   other  BCTC HOP NHAT 31.12.2019 - VN     9            6         203
33  1378235    VNM   other  BCTC HOP NHAT 31.12.2019 - VN    10            0         782
34  1378236    VNM   other  BCTC HOP NHAT 31.12.2019 - VN    10            1         748
35  1378237    VNM   other  BCTC HOP NHAT 31.12.2019 - VN    10            2         729
36  1378238    VNM   other  BCTC HOP NHAT 31.12.2019 - VN    10            3         784
37  1378239    VNM   other  BCTC HOP NHAT 31.12.2019 - VN    10            4         300
38  1378240    VNM   other  BCTC HOP NHAT 31.12.2019 - VN    11            0         797
39  1378241    VNM   other  BCTC HOP NHAT 31.12.2019 - VN    11            1         392
40  1378242    VNM   other  BCTC HOP NHAT 31.12.2019 - VN    12            0         794
41  1378243    VNM   other  BCTC HOP NHAT 31.12.2019 - VN    12            1         702
42  1378244    VNM   other  BCTC HOP NHAT 31.12.2019 - VN    12            2         741
43  1378245    VNM   other  BCTC HOP NHAT 31.12.2019 - VN    12            3         704
44  1378246    VNM   other  BCTC HOP NHAT 31.12.2019 - VN    12            4         572
45  1378247    VNM   other  BCTC HOP NHAT 31.12.2019 - VN    13            0         763
46  1378248    VNM   other  BCTC HOP NHAT 31.12.2019 - VN    13            1         799
47  1378249    VNM   other  BCTC HOP NHAT 31.12.2019 - VN    13            2         765
48  1378250    VNM   other  BCTC HOP NHAT 31.12.2019 - VN    13            3         526
49  1378251    VNM   other  BCTC HOP NHAT 31.12.2019 - VN    14            0         709

## 4. Dữ liệu cấu trúc (DAG path) — `companies` / `financial_line_items` / `financial_ratios` / `disclosures`

In [6]:
for table in ["companies", "financial_line_items", "financial_ratios", "disclosures"]:
    try:
        df = pd.read_sql(f"SELECT * FROM {table} LIMIT 20", engine)
        n_total = pd.read_sql(f"SELECT count(*) AS n FROM {table}", engine)["n"].iloc[0]
        print(f"--- {table}: {n_total:,} dong (hien 20 dau) ---")
        display(df)
    except Exception as e:
        print(f"[canh bao] khong doc duoc {table}: {type(e).__name__}: {e}")
        traceback.print_exc()

--- companies: 222 dong (hien 20 dau) ---

   ticker                                              company_name exchange                              sector                       created_at
0     VNM                                         CTCP Sữa Việt Nam     HOSE                 Tiêu dùng thiết yếu 2026-07-27 10:17:41.540256+00:00
1     SAB  Tổng Công ty cổ phần Bia - Rượu - Nước giải khát Sài Gòn     HOSE                 Tiêu dùng thiết yếu 2026-07-27 10:17:41.540256+00:00
2     MSN                                       CTCP Tập đoàn Masan     HOSE                 Tiêu dùng thiết yếu 2026-07-27 10:17:41.540256+00:00
3     KDC                                        CTCP Tập đoàn KIDO     HOSE                 Tiêu dùng thiết yếu 2026-07-27 10:17:41.540256+00:00
4     VIC                                  Tập đoàn VINGROUP - CTCP     HOSE                        Bất động sản 2026-07-27 10:17:41.540256+00:00
5     VHM                                             CTCP Vinhomes     HOSE                        Bất động sản 2026-07-27 10:17:41.540256+00:00
6     NVL                         CTCP Tập đoàn Đầu tư Địa ốc No Va     HOSE                        Bất động sản 2026-07-27 10:17:41.540256+00:00
7     KDH                  CTCP Đầu tư và Kinh doanh Nhà Khang Điền     HOSE                        Bất động sản 2026-07-27 10:17:41.540256+00:00
8     HPG                                    CTCP Tập đoàn Hòa Phát     HOSE                Công nghiệp chế biến 2026-07-27 10:17:41.540256+00:00
9     GAS                          Tổng Công ty Khí Việt Nam - CTCP     HOSE                Công nghiệp chế biến 2026-07-27 10:17:41.540256+00:00
10    DPM          Tổng công ty Phân bón và Hóa chất Dầu khí - CTCP     HOSE                Công nghiệp chế biến 2026-07-27 10:17:41.540256+00:00
11    DCM               CTCP - Tổng công ty Phân bón Dầu khí Cà Mau     HOSE                Công nghiệp chế biến 2026-07-27 10:17:41.540256+00:00
12    MWG                              CTCP Đầu tư Thế giới Di động     HOSE  Tiêu dùng không thiết yếu (Bán lẻ) 2026-07-27 10:17:41.540256+00:00
13    PNJ                            CTCP Vàng bạc Đá quý Phú Nhuận     HOSE  Tiêu dùng không thiết yếu (Bán lẻ) 2026-07-27 10:17:41.540256+00:00
14    DGW                                          CTCP Thế Giới Số     HOSE  Tiêu dùng không thiết yếu (Bán lẻ) 2026-07-27 10:17:41.540256+00:00
15    FRT                               CTCP Bán lẻ Kỹ thuật số FPT     HOSE  Tiêu dùng không thiết yếu (Bán lẻ) 2026-07-27 10:17:41.540256+00:00
16    ALC                                               CTCP Âu Lạc    UPCOM                          Năng lượng 2026-07-27 10:17:41.540256+00:00
17    A32                                                       A32  UNKNOWN                      Chưa phân loại 2026-07-27 10:17:44.859436+00:00
18   AAAA                                                      AAAA  UNKNOWN                      Chưa phân loại 2026-07-27 10:17:45.080224+00:00
19    AAN                                                       AAN  UNKNOWN                      Chưa phân loại 2026-07-27 10:17:45.450868+00:00

--- financial_line_items: 283,732 dong (hien 20 dau) ---

       id ticker  fiscal_year period ms_code         item_name statement_type consolidation         value unit                       updated_at
0   91047    API         2024     Q1     140  IV. Hàng tồn kho  balance_sheet  consolidated  8.736632e+11  VND 2026-07-27 10:17:56.259173+00:00
1   91048    API         2024     Q2     140  IV. Hàng tồn kho  balance_sheet  consolidated  8.466103e+11  VND 2026-07-27 10:17:56.259173+00:00
2   91049    API         2024     Q3     140  IV. Hàng tồn kho  balance_sheet  consolidated  8.338423e+11  VND 2026-07-27 10:17:56.259173+00:00
3   91050    API         2024     Q4     140  IV. Hàng tồn kho  balance_sheet  consolidated  8.354500e+11  VND 2026-07-27 10:17:56.259173+00:00
4   91051    API         2024     H1     140  IV. Hàng tồn kho  balance_sheet  consolidated  8.480193e+11  VND 2026-07-27 10:17:56.259173+00:00
5   91052    API         2024     9M     140  IV. Hàng tồn kho  balance_sheet  consolidated  8.338423e+11  VND 2026-07-27 10:17:56.259173+00:00
6   91053    API         2025   YEAR     140  IV. Hàng tồn kho  balance_sheet  consolidated  8.044742e+11  VND 2026-07-27 10:17:56.259173+00:00
7   91054    API         2025     Q1     140  IV. Hàng tồn kho  balance_sheet  consolidated  8.140540e+11  VND 2026-07-27 10:17:56.259173+00:00
8   91055    API         2025     Q2     140  IV. Hàng tồn kho  balance_sheet  consolidated  8.089465e+11  VND 2026-07-27 10:17:56.259173+00:00
9   91056    API         2025     Q3     140  IV. Hàng tồn kho  balance_sheet  consolidated  8.082158e+11  VND 2026-07-27 10:17:56.259173+00:00
10  91057    API         2025     Q4     140  IV. Hàng tồn kho  balance_sheet  consolidated  7.942476e+11  VND 2026-07-27 10:17:56.259173+00:00
11  91058    API         2025     H1     140  IV. Hàng tồn kho  balance_sheet  consolidated  8.100493e+11  VND 2026-07-27 10:17:56.259173+00:00
12  91059    API         2025     9M     140  IV. Hàng tồn kho  balance_sheet  consolidated  8.082158e+11  VND 2026-07-27 10:17:56.259173+00:00
13  91060    API         2026     Q1     140  IV. Hàng tồn kho  balance_sheet  consolidated  8.142657e+11  VND 2026-07-27 10:17:56.259173+00:00
14  91061    API         2024   YEAR     141   1. Hàng tồn kho  balance_sheet  consolidated  8.351654e+11  VND 2026-07-27 10:17:56.259173+00:00
15  91062    API         2024     Q1     141   1. Hàng tồn kho  balance_sheet  consolidated  8.736632e+11  VND 2026-07-27 10:17:56.259173+00:00
16  91063    API         2024     Q2     141   1. Hàng tồn kho  balance_sheet  consolidated  8.466103e+11  VND 2026-07-27 10:17:56.259173+00:00
17  91064    API         2024     Q3     141   1. Hàng tồn kho  balance_sheet  consolidated  8.338423e+11  VND 2026-07-27 10:17:56.259173+00:00
18  91065    API         2024     Q4     141   1. Hàng tồn kho  balance_sheet  consolidated  8.354500e+11  VND 2026-07-27 10:17:56.259173+00:00
19  91066    API         2024     H1     141   1. Hàng tồn kho  balance_sheet  consolidated  8.480193e+11  VND 2026-07-27 10:17:56.259173+00:00

--- financial_ratios: 136,369 dong (hien 20 dau) ---

,id,ticker,fiscal_year,period,ratio_group,ratio_name,value,unit,updated_at
0,1,A32,2024,YEAR,NHÓM CHỈ SỐ ĐỊNH GIÁ,Thu nhập trên mỗi cổ phần của 4 quý gần nhất (EPS),5775.00,VNĐ,2026-07-27 10:18:23.288957+00:00
1,2,A32,2025,YEAR,NHÓM CHỈ SỐ ĐỊNH GIÁ,Thu nhập trên mỗi cổ phần của 4 quý gần nhất (EPS),7481.00,VNĐ,2026-07-27 10:18:23.288957+00:00
2,3,A32,2024,YEAR,NHÓM CHỈ SỐ ĐỊNH GIÁ,Giá trị sổ sách của cổ phiếu (BVPS),32525.00,VNĐ,2026-07-27 10:18:23.288957+00:00
3,4,A32,2025,YEAR,NHÓM CHỈ SỐ ĐỊNH GIÁ,Giá trị sổ sách của cổ phiếu (BVPS),33937.00,VNĐ,2026-07-27 10:18:23.288957+00:00
4,5,A32,2024,YEAR,NHÓM CHỈ SỐ ĐỊNH GIÁ,Chỉ số giá thị trường trên thu nhập (P/E),6.61,Lần,2026-07-27 10:18:23.288957+00:00
5,6,A32,2025,YEAR,NHÓM CHỈ SỐ ĐỊNH GIÁ,Chỉ số giá thị trường trên thu nhập (P/E),4.67,Lần,2026-07-27 10:18:23.288957+00:00
6,7,A32,2024,YEAR,NHÓM CHỈ SỐ ĐỊNH GIÁ,Chỉ số giá thị trường trên giá trị sổ sách (P/B),1.17,Lần,2026-07-27 10:18:23.288957+00:00
7,8,A32,2025,YEAR,NHÓM CHỈ SỐ ĐỊNH GIÁ,Chỉ số giá thị trường trên giá trị sổ sách (P/B),1.03,Lần,2026-07-27 10:18:23.288957+00:00
8,9,A32,2024,YEAR,NHÓM CHỈ SỐ ĐỊNH GIÁ,Chỉ số giá thị trường trên doanh thu thuần (P/S),0.36,Lần,2026-07-27 10:18:23.288957+00:00
9,10,A32,2025,YEAR,NHÓM CHỈ SỐ ĐỊNH GIÁ,Chỉ số giá thị trường trên doanh thu thuần (P/S),0.31,Lần,2026-07-27 10:18:23.288957+00:00
10,11,A32,2024,YEAR,NHÓM CHỈ SỐ ĐỊNH GIÁ,Tỷ suất cổ tức,0.09,%,2026-07-27 10:18:23.288957+00:00
11,12,A32,2025,YEAR,NHÓM CHỈ SỐ ĐỊNH GIÁ,Tỷ suất cổ tức,0.06,%,2026-07-27 10:18:23.288957+00:00
12,13,A32,2024,YEAR,NHÓM CHỈ SỐ ĐỊNH GIÁ,Beta,0.08,Lần,2026-07-27 10:18:23.288957+00:00
13,14,A32,2025,YEAR,NHÓM CHỈ SỐ ĐỊNH GIÁ,Beta,-0.03,Lần,2026-07-27 10:18:23.288957+00:00
14,15,A32,2024,YEAR,NHÓM CHỈ SỐ ĐỊNH GIÁ,Giá trị doanh nghiệp trên lợi nhuận trước thuế và lãi vay (EV/EBIT),3.46,Lần,2026-07-27 10:18:23.288957+00:00
15,16,A32,2025,YEAR,NHÓM CHỈ SỐ ĐỊNH GIÁ,Giá trị doanh nghiệp trên lợi nhuận trước thuế và lãi vay (EV/EBIT),3.40,Lần,2026-07-27 10:18:23.288957+00:00
16,17,A32,2024,YEAR,NHÓM CHỈ SỐ SINH LỢI,Tỷ suất lợi nhuận gộp biên,9.95,%,2026-07-27 10:18:23.288957+00:00
17,18,A32,2025,YEAR,NHÓM CHỈ SỐ SINH LỢI,Tỷ suất lợi nhuận gộp biên,10.34,%,2026-07-27 10:18:23.288957+00:00
18,19,A32,2024,YEAR,NHÓM CHỈ SỐ SINH LỢI,Tỷ lệ lãi EBIT,6.28,%,2026-07-27 10:18:23.288957+00:00
19,20,A32,2025,YEAR,NHÓM CHỈ SỐ SINH LỢI,Tỷ lệ lãi EBIT,7.87,%,2026-07-27 10:18:23.288957+00:00

--- disclosures: 3,155 dong (hien 20 dau) ---

,id,ticker,fiscal_year,period,consolidation,report_type,audit_status,auditor,audit_opinion,disclosure_date,signed_date,source_pdf_path,structure_valid,updated_at
0,1,A32,2024,YEAR,standalone,nam,Kiểm toán,VAE,Chấp nhận toàn phần,2025-03-04,2025-02-26,None,None,2026-07-27 10:17:44.859436+00:00
1,2,A32,2025,YEAR,standalone,nam,Kiểm toán,VAE,Chấp nhận toàn phần,2026-04-01,2026-03-28,None,None,2026-07-27 10:17:44.859436+00:00
2,1842,BTP,2024,YEAR,standalone,nam,Kiểm toán,Deloitte,Chấp nhận toàn phần,2025-03-27,2025-03-25,None,None,2026-07-27 10:18:06.444263+00:00
3,1843,BTP,2024,Q1,standalone,quy,Chưa kiểm toán,None,None,2024-04-16,None,None,None,2026-07-27 10:18:06.444263+00:00
4,1844,BTP,2024,Q2,standalone,quy,Chưa kiểm toán,None,None,2024-07-17,None,None,None,2026-07-27 10:18:06.444263+00:00
5,1845,BTP,2024,Q3,standalone,quy,Chưa kiểm toán,None,None,2024-10-18,None,None,None,2026-07-27 10:18:06.444263+00:00
6,1846,BTP,2024,Q4,standalone,quy,Chưa kiểm toán,None,None,2025-01-21,None,None,None,2026-07-27 10:18:06.444263+00:00
7,1847,BTP,2024,H1,standalone,ban_nien,Soát xét,Deloitte,Chấp nhận toàn phần,2024-08-15,2024-08-14,None,None,2026-07-27 10:18:06.444263+00:00
8,1848,BTP,2024,9M,standalone,ban_nien,Chưa kiểm toán,None,None,2024-10-18,None,None,None,2026-07-27 10:18:06.444263+00:00
9,1849,BTP,2025,YEAR,standalone,nam,Kiểm toán,Deloitte,Chấp nhận toàn phần,2026-04-01,2026-03-31,None,None,2026-07-27 10:18:06.444263+00:00
10,1850,BTP,2025,Q1,standalone,quy,Chưa kiểm toán,None,None,2025-04-19,None,None,None,2026-07-27 10:18:06.444263+00:00
11,1851,BTP,2025,Q2,standalone,quy,Chưa kiểm toán,None,None,2025-07-17,None,None,None,2026-07-27 10:18:06.444263+00:00
12,1852,BTP,2025,Q3,standalone,quy,Chưa kiểm toán,None,None,2025-10-20,None,None,None,2026-07-27 10:18:06.444263+00:00
13,1853,BTP,2025,Q4,standalone,quy,Chưa kiểm toán,None,None,2026-01-20,None,None,None,2026-07-27 10:18:06.444263+00:00
14,1854,BTP,2025,H1,standalone,ban_nien,Soát xét,Deloitte,Chấp nhận toàn phần,2025-08-14,2025-08-14,None,None,2026-07-27 10:18:06.444263+00:00
15,1855,BTP,2025,9M,standalone,ban_nien,Chưa kiểm toán,None,None,2025-10-20,None,None,None,2026-07-27 10:18:06.444263+00:00
16,1856,BTP,2026,Q1,standalone,quy,Chưa kiểm toán,None,None,2026-04-22,None,None,None,2026-07-27 10:18:06.444263+00:00
17,18,AAAA,2024,H1,standalone,ban_nien,Chưa kiểm toán,None,None,2025-01-15,None,None,None,2026-07-27 10:17:45.080224+00:00
18,19,AAAA,2025,Q2,standalone,quy,Chưa kiểm toán,None,None,2026-01-13,None,None,None,2026-07-27 10:17:45.080224+00:00
19,20,AAAA,2025,H1,standalone,ban_nien,Chưa kiểm toán,None,None,2026-01-13,None,None,None,2026-07-27 10:17:45.080224+00:00

## 5. `predictive_features` / `predictive_split_manifest` / `causal_panel_snapshot` / `causal_experiment_runs`

Các bảng phục vụ nhánh PREDICTIVE/CAUSAL (nếu chưa chạy các script tương ứng, bảng sẽ rỗng
- không phải lỗi).

In [7]:
for table in ["predictive_features", "predictive_split_manifest", "causal_panel_snapshot", "causal_experiment_runs"]:
    try:
        df = pd.read_sql(f"SELECT * FROM {table} LIMIT 20", engine)
        n_total = pd.read_sql(f"SELECT count(*) AS n FROM {table}", engine)["n"].iloc[0]
        print(f"--- {table}: {n_total:,} dong (hien 20 dau) ---")
        display(df)
    except Exception as e:
        print(f"[canh bao] khong doc duoc {table}: {type(e).__name__}: {e}")
        traceback.print_exc()

--- predictive_features: 0 dong (hien 20 dau) ---

Empty DataFrame
Columns: [id, feature_version, ticker, fiscal_year, period, consolidation, sector, exchange, total_assets, total_liabilities, total_equity, current_assets, current_liabilities, inventory, revenue, cogs, gross_profit, profit_before_tax, net_profit, operating_cash_flow, leverage, current_ratio, gross_margin, net_margin, asset_turnover, ocf_to_revenue, total_assets_lag1, total_liabilities_lag1, total_equity_lag1, current_assets_lag1, current_liabilities_lag1, inventory_lag1, revenue_lag1, cogs_lag1, gross_profit_lag1, profit_before_tax_lag1, net_profit_lag1, operating_cash_flow_lag1, leverage_lag1, current_ratio_lag1, gross_margin_lag1, net_margin_lag1, asset_turnover_lag1, ocf_to_revenue_lag1, revenue_growth_yoy, net_profit_growth_yoy, total_assets_growth_yoy, cpi_annual_avg, gdp_growth_annual_avg, gold_price_annual_avg, usdvnd_annual_avg, oil_price_annual_avg, information_cutoff, target_col, horizon, target_value, eligible_for_training, created_at, updated_at, target_observed_at, target_release_date, feature_created_at, feature_hash, source_snapshot_version]
Index: []

[0 rows x 64 columns]

--- predictive_split_manifest: 0 dong (hien 20 dau) ---

Empty DataFrame
Columns: [id, split_manifest_version, feature_version, ticker, fiscal_year, period, consolidation, target_col, horizon, information_cutoff, split, frozen_at]
Index: []

--- causal_panel_snapshot: 0 dong (hien 20 dau) ---

Empty DataFrame
Columns: [id, snapshot_version, ticker, fiscal_year, period, consolidation, sector, exchange, total_assets, total_liabilities, total_equity, current_assets, current_liabilities, inventory, revenue, cogs, gross_profit, profit_before_tax, net_profit, operating_cash_flow, leverage, current_ratio, gross_margin, net_margin, asset_turnover, ocf_to_revenue, cpi_annual_avg, gdp_growth_annual_avg, gold_price_annual_avg, usdvnd_annual_avg, oil_price_annual_avg, eligible_sample, exclusion_reason, created_at]
Index: []

--- causal_experiment_runs: 0 dong (hien 20 dau) ---

Empty DataFrame
Columns: [id, snapshot_version, source_dataset_version, treatment_name, outcome_name, covariates, estimator, nuisance_model, random_seed, bootstrap_iterations, min_sample_threshold, code_commit, n, n_treated, n_control, point_estimate, ci_low, ci_high, confidence_label, ok, error_message, created_at]
Index: []

## 6. `macro_indicators` / `company_price_snapshot` (market-factor & giá)

In [8]:
for table in ["macro_indicators", "company_price_snapshot"]:
    try:
        df = pd.read_sql(f"SELECT * FROM {table} LIMIT 20", engine)
        n_total = pd.read_sql(f"SELECT count(*) AS n FROM {table}", engine)["n"].iloc[0]
        print(f"--- {table}: {n_total:,} dong (hien 20 dau) ---")
        display(df)
    except Exception as e:
        print(f"[canh bao] khong doc duoc {table}: {type(e).__name__}: {e}")
        traceback.print_exc()

--- macro_indicators: 264 dong (hien 20 dau) ---

    id     category    indicator_name  unit period_type  fiscal_year period    value  source_file                       updated_at release_date
0    1  MKT_VNINDEX  VN-Index (close)  điểm       DAILY         2025  D0728  1557.42  vnstock_vci 2026-07-27 10:17:47.576479+00:00         None
1    2  MKT_VNINDEX  VN-Index (close)  điểm       DAILY         2025  D0729  1493.41  vnstock_vci 2026-07-27 10:17:47.576479+00:00         None
2    3  MKT_VNINDEX  VN-Index (close)  điểm       DAILY         2025  D0730  1507.63  vnstock_vci 2026-07-27 10:17:47.576479+00:00         None
3    4  MKT_VNINDEX  VN-Index (close)  điểm       DAILY         2025  D0731  1502.52  vnstock_vci 2026-07-27 10:17:47.576479+00:00         None
4    5  MKT_VNINDEX  VN-Index (close)  điểm       DAILY         2025  D0801  1495.21  vnstock_vci 2026-07-27 10:17:47.576479+00:00         None
5    6  MKT_VNINDEX  VN-Index (close)  điểm       DAILY         2025  D0804  1528.19  vnstock_vci 2026-07-27 10:17:47.576479+00:00         None
6    7  MKT_VNINDEX  VN-Index (close)  điểm       DAILY         2025  D0805  1547.15  vnstock_vci 2026-07-27 10:17:47.576479+00:00         None
7    8  MKT_VNINDEX  VN-Index (close)  điểm       DAILY         2025  D0806  1573.71  vnstock_vci 2026-07-27 10:17:47.576479+00:00         None
8    9  MKT_VNINDEX  VN-Index (close)  điểm       DAILY         2025  D0807  1581.81  vnstock_vci 2026-07-27 10:17:47.576479+00:00         None
9   10  MKT_VNINDEX  VN-Index (close)  điểm       DAILY         2025  D0808  1584.95  vnstock_vci 2026-07-27 10:17:47.576479+00:00         None
10  11  MKT_VNINDEX  VN-Index (close)  điểm       DAILY         2025  D0811  1596.86  vnstock_vci 2026-07-27 10:17:47.576479+00:00         None
11  12  MKT_VNINDEX  VN-Index (close)  điểm       DAILY         2025  D0812  1608.22  vnstock_vci 2026-07-27 10:17:47.576479+00:00         None
12  13  MKT_VNINDEX  VN-Index (close)  điểm       DAILY         2025  D0813  1611.60  vnstock_vci 2026-07-27 10:17:47.576479+00:00         None
13  14  MKT_VNINDEX  VN-Index (close)  điểm       DAILY         2025  D0814  1640.69  vnstock_vci 2026-07-27 10:17:47.576479+00:00         None
14  15  MKT_VNINDEX  VN-Index (close)  điểm       DAILY         2025  D0815  1630.00  vnstock_vci 2026-07-27 10:17:47.576479+00:00         None
15  16  MKT_VNINDEX  VN-Index (close)  điểm       DAILY         2025  D0818  1636.37  vnstock_vci 2026-07-27 10:17:47.576479+00:00         None
16  17  MKT_VNINDEX  VN-Index (close)  điểm       DAILY         2025  D0819  1654.20  vnstock_vci 2026-07-27 10:17:47.576479+00:00         None
17  18  MKT_VNINDEX  VN-Index (close)  điểm       DAILY         2025  D0820  1664.36  vnstock_vci 2026-07-27 10:17:47.576479+00:00         None
18  19  MKT_VNINDEX  VN-Index (close)  điểm       DAILY         2025  D0821  1688.00  vnstock_vci 2026-07-27 10:17:47.576479+00:00         None
19  20  MKT_VNINDEX  VN-Index (close)  điểm       DAILY         2025  D0822  1645.47  vnstock_vci 2026-07-27 10:17:47.576479+00:00         None

--- company_price_snapshot: 39,575 dong (hien 20 dau) ---

    id ticker  trade_date  open_price  high_price  low_price  close_price  volume       source                       updated_at
0    1    A32  2025-07-30       32.54       32.64      32.54        32.64     500  vnstock_kbs 2026-07-27 10:17:48.222030+00:00
1    2    A32  2025-07-31       32.82       32.82      32.82        32.82     100  vnstock_kbs 2026-07-27 10:17:48.222030+00:00
2    3    A32  2025-08-01       32.73       33.01      32.73        33.01     400  vnstock_kbs 2026-07-27 10:17:48.222030+00:00
3    4    A32  2025-08-04       32.73       32.73      32.73        32.73     200  vnstock_kbs 2026-07-27 10:17:48.222030+00:00
4    5    A32  2025-08-05       32.73       32.73      32.73        32.73     200  vnstock_kbs 2026-07-27 10:17:48.222030+00:00
5    6    A32  2025-08-06       33.01       36.54      33.01        36.54     200  vnstock_kbs 2026-07-27 10:17:48.222030+00:00
6    7    A32  2025-08-07       33.20       33.20      33.20        33.20     100  vnstock_kbs 2026-07-27 10:17:48.222030+00:00
7    8    A32  2025-08-08       33.20       33.20      33.20        33.20     100  vnstock_kbs 2026-07-27 10:17:48.222030+00:00
8    9    A32  2025-08-11       34.31       34.31      34.31        34.31     100  vnstock_kbs 2026-07-27 10:17:48.222030+00:00
9   10    A32  2025-08-12       34.31       34.31      34.31        34.31     100  vnstock_kbs 2026-07-27 10:17:48.222030+00:00
10  11    A32  2025-08-14       34.31       34.31      33.94        33.94     200  vnstock_kbs 2026-07-27 10:17:48.222030+00:00
11  12    A32  2025-08-18       34.31       34.31      34.31        34.31     100  vnstock_kbs 2026-07-27 10:17:48.222030+00:00
12  13    A32  2025-08-21       33.47       33.47      33.47        33.47     100  vnstock_kbs 2026-07-27 10:17:48.222030+00:00
13  14    A32  2025-08-26       33.01       33.01      33.01        33.01     200  vnstock_kbs 2026-07-27 10:17:48.222030+00:00
14  15    A32  2025-09-03       34.40       34.40      34.40        34.40     100  vnstock_kbs 2026-07-27 10:17:48.222030+00:00
15  16    A32  2025-09-08       32.54       32.54      32.54        32.54     100  vnstock_kbs 2026-07-27 10:17:48.222030+00:00
16  17    A32  2025-09-15       33.94       33.94      33.94        33.94     100  vnstock_kbs 2026-07-27 10:17:48.222030+00:00
17  18    A32  2025-09-19       33.75       34.40      33.75        34.40    1200  vnstock_kbs 2026-07-27 10:17:48.222030+00:00
18  19    A32  2025-09-23       32.73       32.73      32.54        32.54     800  vnstock_kbs 2026-07-27 10:17:48.222030+00:00
19  20    A32  2025-09-24       32.54       32.54      32.54        32.54     100  vnstock_kbs 2026-07-27 10:17:48.222030+00:00

## 7. Xem bảng bất kỳ (tự sửa tên bảng)

Đổi `TABLE_NAME` bên dưới thành tên bất kỳ trong danh sách ở mục 1, chạy lại cell.

In [9]:
TABLE_NAME = "pdf_documents"  # doi ten bang o day

try:
    df = pd.read_sql(f"SELECT * FROM {TABLE_NAME} LIMIT 50", engine)
    print(f"{TABLE_NAME}: hien {len(df)} dong dau")
    display(df)
except Exception as e:
    print(f"[canh bao] khong doc duoc {TABLE_NAME}: {type(e).__name__}: {e}")
    traceback.print_exc()

pdf_documents: hien 50 dong dau

,id,source_file,pdf_hash,ticker,doctype,fiscal_year,n_pages_total,extraction_version,extracted_at,document_version,is_active,linked_disclosure_id,updated_at
0,2,01.-Thong-bao-moi-hop-DHDCD-2023_VN-Final.pdf,7243c1bdf983c43976d2915b76b835d2b902af79d475e07accfa6ff12af79922,UNKNOWN,other,2023.0,1,,2026-07-30 07:36:06.838922+00:00,1,True,NaN,2026-07-30 07:36:06.838922+00:00
1,3,01.-Thong-bao-moi-hop-DHDCD-2024_VN-Final.pdf,d6736c805129c97eec9921c8587313c5effc5cf032c7abe68669d1fa175377a8,UNKNOWN,other,2024.0,1,,2026-07-30 07:36:06.838922+00:00,1,True,NaN,2026-07-30 07:36:06.838922+00:00
2,4,04.-HDSD-Bvote-cho-CD-VN.pdf,065c8a577a8ff57cf4db37a25e518cf6477893bbbd904c75a21d4b3080766df5,UNKNOWN,other,NaN,6,,2026-07-30 07:36:06.838922+00:00,1,True,NaN,2026-07-30 07:36:06.838922+00:00
3,5,0_Ban_CBTT_Tai_lieu_AGM_2026_f295e68b32.pdf,63fa42bdbe4a098eddf6eccfe025b8747ca303da8b39a6f78ab43b1f06188177,UNKNOWN,other,2026.0,1,,2026-07-30 07:36:06.838922+00:00,1,True,NaN,2026-07-30 07:36:06.838922+00:00
4,6,10_AGM_2026_Quy_che_to_chuc_dai_hoi_5765b92317.pdf,b20fb9a9051e3179c29c439ad71a224409aae56d1e28ca6149d452a445e92349,UNKNOWN,other,2026.0,17,,2026-07-30 07:36:06.838922+00:00,1,True,NaN,2026-07-30 07:36:06.838922+00:00
5,343,01.-Thong-bao-moi-hop-DHDCD-2023_VN-Final,7243c1bdf983c43976d2915b76b835d2b902af79d475e07accfa6ff12af79922,UNKNOWN,other,2023.0,1,,2026-07-30 08:43:37.991717+00:00,1,True,NaN,2026-07-30 08:43:37.991717+00:00
6,7,10_aah_2024_5_4_bbab271_12__to_trinh_kqsxkd_signed.pdf,3fd829beeaaaab9f508c9e21d28ef1146b55664083db5b646f9b187b673d654b,AAH,other,2024.0,1,,2026-07-30 07:36:06.838922+00:00,1,True,38.0,2026-07-30 07:36:06.838922+00:00
7,8,11_AGM_2026_Notice_of_candidate_nomination_59bf87a429.pdf,1b81a86045b84d4f7e0b2ab4e2d6aa562bfcf994bda8c7ee894465029e0d96d1,UNKNOWN,other,2026.0,1,,2026-07-30 07:36:06.838922+00:00,1,True,NaN,2026-07-30 07:36:06.838922+00:00
8,9,11_AGM_2026_Thong_bao_de_cu_ung_cu_HDQT_VN_f5763c4c27.pdf,667a6c9d407dac2945f1bbdc6e58eae855dbfa01564edc239c3b3f8700973860,UNKNOWN,other,2026.0,1,,2026-07-30 07:36:06.838922+00:00,1,True,NaN,2026-07-30 07:36:06.838922+00:00
9,344,01.-Thong-bao-moi-hop-DHDCD-2024_VN-Final,d6736c805129c97eec9921c8587313c5effc5cf032c7abe68669d1fa175377a8,UNKNOWN,other,2024.0,1,,2026-07-30 08:43:37.991717+00:00,1,True,NaN,2026-07-30 08:43:37.991717+00:00
10,10,11_aah_2024_5_4_c3757c1_08__bc_ban_tgd_signed.pdf,3ffa767987072af0fd8297c3e2ea36931fd05a3ca387519a077676d7d82f1749,AAH,other,2024.0,4,,2026-07-30 07:36:06.838922+00:00,1,True,38.0,2026-07-30 07:36:06.838922+00:00
11,11,12_VNM_AGM_2026_Mau_1_A_Thu_de_cu_cua_co_dong_VN_Co_dong_don_le_10b9d06fd2.pdf,e8def24080e3e56c136d6d0e7bd607bb7a2baa6a156a9f55b5eaf6913d70ab1c,VNM,other,2026.0,1,,2026-07-30 07:36:06.838922+00:00,1,True,NaN,2026-07-30 07:36:06.838922+00:00
12,12,13_VNM_AGM_2026_Mau_1_B_Thu_de_cu_cua_co_dong_VN_Co_dong_nhom_0c507f3faa.pdf,b9209e00e7bae2b0eb96f1170c45308ed25aca4f48c5ce8220ffb51bf32bd8ff,VNM,other,2026.0,1,,2026-07-30 07:36:06.838922+00:00,1,True,NaN,2026-07-30 07:36:06.838922+00:00
13,345,04.-HDSD-Bvote-cho-CD-VN,065c8a577a8ff57cf4db37a25e518cf6477893bbbd904c75a21d4b3080766df5,UNKNOWN,other,NaN,6,,2026-07-30 08:43:37.991717+00:00,1,True,NaN,2026-07-30 08:43:37.991717+00:00
14,13,13_aah_2024_5_4_f5db49e_02__bbh_dhdcd_signed.pdf,d53ba2bf683f12dd0dd35be1cbe392e5488cc60146f95ff77e0033852385b051,AAH,other,2024.0,8,,2026-07-30 07:36:06.838922+00:00,1,True,38.0,2026-07-30 07:36:06.838922+00:00
15,14,14_VNM_AGM_2026_Form_2_Candidate_Profile_da5c06e639.pdf,55ddd526f6cd86437ff6e21d3d286527bc56f2552acb9f5fc24e549218942355,VNM,other,2026.0,2,,2026-07-30 07:36:06.838922+00:00,1,True,NaN,2026-07-30 07:36:06.838922+00:00
16,15,14_VNM_AGM_2026_Mau_02_So_yeu_ly_lich_VN_777a33a885.pdf,604d053930859f38637b02dbfd6feb734ddd6fb15685cdbb6b99c90038f04e04,VNM,other,2026.0,2,,2026-07-30 07:36:06.838922+00:00,1,True,NaN,2026-07-30 07:36:06.838922+00:00
17,16,15_VNM_AGM_2026_Mau_03_Ke_khai_thong_tin_ung_vien_VN_a1a8c0b743.pdf,33288cc338fb99851edc72334753bff12a54702760c90c88f5b5433432fa3b39,VNM,other,2026.0,3,,2026-07-30 07:36:06.838922+00:00,1,True,NaN,2026-07-30 07:36:06.838922+00:00
18,17,1604_ENG_VCB_Annual-Report-2025_v2.pdf,63988b347b3743391dfec3647fdcdd1f2b06af09ead9a9f52c8bf8fd86352a27,UNKNOWN,other,2025.0,112,,2026-07-30 07:36:06.838922+00:00,1,True,NaN,2026-07-30 07:36:06.838922+00:00
19,18,1_VNM_AGM_2026_AGM_Invitation_Letter_2adb448d1c.pdf,38ee680bdc7c6cebf49ddbf5ac8f4df19f430a86bc59c678a778e00268f1e0c0,VNM,other,2026.0,1,,2026-07-30 07:36:06.838922+00:00,1,True,NaN,2026-07-30 07:36:06.838922+00:00
20,19,1_VNM_AGM_2026_Thu_moi_hop_DHDCD_VN_bdeabe34dd.pdf,88346c79946a83fa14014638267e37d6778fbbcea156c2616ce1b651bec9b640,VNM,other,2026.0,1,,2026-07-30 07:36:06.838922+00:00,1,True,NaN,2026-07-30 07:36:06.838922+00:00
21,346,0_Ban_CBTT_Tai_lieu_AGM_2026_f295e68b32,63fa42bdbe4a098eddf6eccfe025b8747ca303da8b39a6f78ab43b1f06188177,UNKNOWN,other,2026.0,1,,2026-07-30 08:43:37.991717+00:00,1,True,NaN,2026-07-30 08:43:37.991717+00:00
22,20,1_aah_2024_7_22_24641ac_cbtt_0805da_ky.pdf,1807525f6d1c36cac8aeeac61cf4335b64f0bf915738a44e9b4d683522b90701,AAH,other,2024.0,5,,2026-07-30 07:36:06.838922+00:00,1,True,38.0,2026-07-30 07:36:06.838922+00:00
23,347,10_AGM_2026_Quy_che_to_chuc_dai_hoi_5765b92317,b20fb9a9051e3179c29c439ad71a224409aae56d1e28ca6149d452a445e92349,UNKNOWN,other,2026.0,17,,2026-07-30 08:43:37.991717+00:00,1,True,NaN,2026-07-30 08:43:37.991717+00:00
24,21,1_aah_2024_8_19_33a98dd_giai_trinh_chenh_lech_ln_va_ln_tu_lo_sang_lai_cung_k...,09964ea2b0baa3caeeda3670f2cd03fb60ebfb951cb45ccdadce1effff23a1b0,AAH,kqkd_explanation,2024.0,2,,2026-07-30 07:36:06.838922+00:00,1,True,38.0,2026-07-30 07:36:06.838922+00:00
25,348,10_aah_2024_5_4_bbab271_12__to_trinh_kqsxkd_signed,3fd829beeaaaab9f508c9e21d28ef1146b55664083db5b646f9b187b673d654b,AAH,other,2024.0,1,,2026-07-30 08:43:37.991717+00:00,1,True,38.0,2026-07-30 09:39:33.199265+00:00
26,22,1_aah_2025_2_7_1639a0f_vi_baocaoquantri_2024.pdf,994510d751fbda6b2f3698f38981d2b9880fa396a9ed67da40735c6c8181ec1c,AAH,governance_report,2024.0,32,,2026-07-30 07:36:06.838922+00:00,1,True,38.0,2026-07-30 07:36:06.838922+00:00
27,23,1_aah_2025_5_6_09df974_vi__tailieuhopdaihoidongcodongthuongnien_2025_l2.pdf,9e7366169d8c88d0ccc16b9e09b9f1b98df45d785132e998b1d8385d91b1278d,AAH,other,2025.0,58,,2026-07-30 07:36:06.838922+00:00,1,True,45.0,2026-07-30 07:36:06.838922+00:00
28,349,11_AGM_2026_Notice_of_candidate_nomination_59bf87a429,1b81a86045b84d4f7e0b2ab4e2d6aa562bfcf994bda8c7ee894465029e0d96d1,UNKNOWN,other,2026.0,1,,2026-07-30 08:43:37.991717+00:00,1,True,NaN,2026-07-30 08:43:37.991717+00:00
29,24,1_aah_2026_4_23_724926f_vi_baocaotaichinh_q1_2026_.pdf,26a17f47acbe7069aa7387dcb3e5e48b43d7914129c855b2283c941b49ba8e06,AAH,financial_statement,2026.0,29,,2026-07-30 07:36:06.838922+00:00,1,True,52.0,2026-07-30 07:36:06.838922+00:00
30,350,11_AGM_2026_Thong_bao_de_cu_ung_cu_HDQT_VN_f5763c4c27,667a6c9d407dac2945f1bbdc6e58eae855dbfa01564edc239c3b3f8700973860,UNKNOWN,other,2026.0,1,,2026-07-30 08:43:37.991717+00:00,1,True,NaN,2026-07-30 08:43:37.991717+00:00
31,25,1_aah_2026_4_3_08378a4_vi_baocaotaichinh_kiemtoan_2025.pdf,9ff852607ef968b66718db980f21ea77a2ea790a1ce15fee79e46fac76d3ecc6,AAH,financial_statement,2025.0,40,,2026-07-30 07:36:06.838922+00:00,1,True,45.0,2026-07-30 07:36:06.838922+00:00
32,351,11_aah_2024_5_4_c3757c1_08__bc_ban_tgd_signed,3ffa767987072af0fd8297c3e2ea36931fd05a3ca387519a077676d7d82f1749,AAH,other,2024.0,4,,2026-07-30 08:43:37.991717+00:00,1,True,38.0,2026-07-30 09:39:33.199265+00:00
33,26,1_aah_2026_7_1_26ab5f1_vi_nghiquyetdhdcdbathuong_p2.pdf,92d96b10f6c3c873cfb43858e38096abd9a32e4341da82040aa41d892129b629,AAH,agm_resolution,2026.0,25,,2026-07-30 07:36:06.838922+00:00,1,True,52.0,2026-07-30 07:36:06.838922+00:00
34,27,1_aah_2026_7_21_08a48ed_en_financialstatements_q2_2026.pdf,204fb067276323ed44b87a6b4845d30a55a3615e2e0f27790e962694e3e591aa,AAH,other,2026.0,29,,2026-07-30 07:36:06.838922+00:00,1,True,52.0,2026-07-30 07:36:06.838922+00:00
35,352,12_VNM_AGM_2026_Mau_1_A_Thu_de_cu_cua_co_dong_VN_Co_dong_don_le_10b9d06fd2,e8def24080e3e56c136d6d0e7bd607bb7a2baa6a156a9f55b5eaf6913d70ab1c,VNM,other,2026.0,1,,2026-07-30 08:43:37.991717+00:00,1,True,NaN,2026-07-30 08:43:37.991717+00:00
36,353,13_VNM_AGM_2026_Mau_1_B_Thu_de_cu_cua_co_dong_VN_Co_dong_nhom_0c507f3faa,b9209e00e7bae2b0eb96f1170c45308ed25aca4f48c5ce8220ffb51bf32bd8ff,VNM,other,2026.0,1,,2026-07-30 08:43:37.991717+00:00,1,True,NaN,2026-07-30 08:43:37.991717+00:00
37,28,1_aas_2024_7_24_627631e_bctc_quy_2_2024_cks.pdf,c28083dcd8a3091c51860563ee295f479bad067d7909a829a5ae1bd0883d4092,AAS,other,2024.0,37,,2026-07-30 07:36:06.838922+00:00,1,True,65.0,2026-07-30 07:36:06.838922+00:00
38,354,13_aah_2024_5_4_f5db49e_02__bbh_dhdcd_signed,d53ba2bf683f12dd0dd35be1cbe392e5488cc60146f95ff77e0033852385b051,AAH,other,2024.0,8,,2026-07-30 08:43:37.991717+00:00,1,True,38.0,2026-07-30 09:39:33.199265+00:00
39,29,1_aas_2025_7_30_4343a20_vi_baocaoquantri_bannien2025.pdf,9752a34ccdb5cae489185ac1f6abe97f225dd763d1737a3f2a358762e291e36c,AAS,governance_report,2025.0,27,,2026-07-30 07:36:06.838922+00:00,1,True,72.0,2026-07-30 07:36:06.838922+00:00
40,30,1_aas_2026_2_3_14c7b1b_vi_baocaoquantri_nam2025.pdf,66f571b6e6a28c190922875e267eb92fb25f689e93b1feaa6688ae562ecfdbca,AAS,governance_report,2025.0,18,,2026-07-30 07:36:06.838922+00:00,1,True,72.0,2026-07-30 07:36:06.838922+00:00
41,355,14_VNM_AGM_2026_Form_2_Candidate_Profile_da5c06e639,55ddd526f6cd86437ff6e21d3d286527bc56f2552acb9f5fc24e549218942355,VNM,other,2026.0,2,,2026-07-30 08:43:37.991717+00:00,1,True,NaN,2026-07-30 08:43:37.991717+00:00
42,31,1_aav_2025_10_30_79d5dcc_vi_baocaotaichinh_q3_2025 (1).pdf,b9417448b905eb1746ac4cc2a4d4300b071bbb478ca80bfe4584ed4c83af85cd,AAV,financial_statement,2025.0,41,,2026-07-30 07:36:06.838922+00:00,1,True,102.0,2026-07-30 07:36:06.838922+00:00
43,356,14_VNM_AGM_2026_Mau_02_So_yeu_ly_lich_VN_777a33a885,604d053930859f38637b02dbfd6feb734ddd6fb15685cdbb6b99c90038f04e04,VNM,other,2026.0,2,,2026-07-30 08:43:37.991717+00:00,1,True,NaN,2026-07-30 08:43:37.991717+00:00
44,32,1_aav_2025_10_30_79d5dcc_vi_baocaotaichinh_q3_2025.pdf,b9417448b905eb1746ac4cc2a4d4300b071bbb478ca80bfe4584ed4c83af85cd,AAV,financial_statement,2025.0,41,,2026-07-30 07:36:06.838922+00:00,1,True,102.0,2026-07-30 07:36:06.838922+00:00
45,357,15_VNM_AGM_2026_Mau_03_Ke_khai_thong_tin_ung_vien_VN_a1a8c0b743,33288cc338fb99851edc72334753bff12a54702760c90c88f5b5433432fa3b39,VNM,other,2026.0,3,,2026-07-30 08:43:37.991717+00:00,1,True,NaN,2026-07-30 08:43:37.991717+00:00
46,33,1_aav_2025_2_5_9b1131a_vi_baocaotaichinh_q4_2024.pdf,db81039562979fe1e54d9b98f23ddbf6e40e0c3488abf763bae8a7231594db3e,AAV,financial_statement,2024.0,43,,2026-07-30 07:36:06.838922+00:00,1,True,95.0,2026-07-30 07:36:06.838922+00:00
47,358,1604_ENG_VCB_Annual-Report-2025_v2,63988b347b3743391dfec3647fdcdd1f2b06af09ead9a9f52c8bf8fd86352a27,UNKNOWN,other,2025.0,112,,2026-07-30 08:43:37.991717+00:00,1,True,NaN,2026-07-30 08:43:37.991717+00:00
48,34,1_aav_2025_4_28_4e05031_vi_baocaotaichinh_q1_2025.pdf,28a1e6446d9cfac3902a12f950d1a79a93e4ff8fa7eac70499efc8b32a9f71bc,AAV,financial_statement,2025.0,39,,2026-07-30 07:36:06.838922+00:00,1,True,102.0,2026-07-30 07:36:06.838922+00:00
49,359,1_VNM_AGM_2026_AGM_Invitation_Letter_2adb448d1c,38ee680bdc7c6cebf49ddbf5ac8f4df19f430a86bc59c678a778e00268f1e0c0,VNM,other,2026.0,1,,2026-07-30 08:43:37.991717+00:00,1,True,NaN,2026-07-30 08:43:37.991717+00:00